name: Cypress Tests

on: [push, pull_request]

jobs:
  cypress_test:
    name: Run all cypress test using Firebase Emulator Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Install Firebase Emulator Suite
        run: npm install -g firebase-tools
      - name: Install dependencies
        run: npm install
      - name: Run tests
        env: FIREBASE_PROJECT_ID: ${{secrets.FIREBASE_PROJECT_ID}}
        run: firebase emulators:exec --only auth --project "$FIREBASE_PROJECT_ID" 'npm run testCypress'

