name: Cypress Tests

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests@- uses: actions/setup-node@v1
      - uses: actions/setup-node@v1
      - run: npm ci
      - name: Setup emulators and server & run tests
        run: |
          npm start 
          npm install -g firebase-tools
          firebase emulators:exec --only auth \"npx cypress run\"

